import { useEffect, useState } from 'react';
import {
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Button,
  TextField,
  MenuItem,
  Stack,
  FormControlLabel,
  Switch,
  Checkbox,
  Alert,
  Typography,
  Divider,
  Link,
} from '@mui/material';
import { AddCircleOutline as AddCircleOutlineIcon } from '@mui/icons-material';
import { useTranslation } from 'react-i18next';
import { workerService } from '../../services/workerService';
import { supervisorService } from '../../services/supervisorService';
import { companyService } from '../../services/companyService';
import type { CompanyType, Worker } from '../../types/worker';
import type { Company } from '../../types/company';
import { CompanyDialog } from '../Companies/CompanyDialog';

type Mode = 'create' | 'edit';

interface Props {
  open: boolean;
  mode: Mode;
  initial?: Worker | null;
  onClose: () => void;
  onSaved: () => void;
}

interface FormState {
  employeeCode: string;
  fullName: string;
  phone: string;
  email: string;
  companyName: string;
  companyType: CompanyType;
  roleInPlant: string;
  hireDate: string;
  notes: string;
  isActive: boolean;
  // V13
  isWorkerInPlant: boolean;
  isSupervisor: boolean;
  isCompanyManager: boolean;
  supervisorId: number | '';
  backupSupervisorId: number | '';
  companyId: number | '';
  lastPrlTrainingDate: string;
  prlValidMonths: number;
  supervisorNotes: string;
}

const EMPTY: FormState = {
  employeeCode: '',
  fullName: '',
  phone: '',
  email: '',
  companyName: '',
  companyType: 'INTERNAL',
  roleInPlant: '',
  hireDate: '',
  notes: '',
  isActive: true,
  isWorkerInPlant: true,
  isSupervisor: false,
  isCompanyManager: false,
  supervisorId: '',
  backupSupervisorId: '',
  companyId: '',
  lastPrlTrainingDate: '',
  prlValidMonths: 12,
  supervisorNotes: '',
};

export function WorkerDialog({ open, mode, initial, onClose, onSaved }: Props) {
  const { t } = useTranslation();
  const [form, setForm] = useState<FormState>(EMPTY);
  const [supervisors, setSupervisors] = useState<Worker[]>([]);
  const [companies, setCompanies] = useState<Company[]>([]);
  const [loadingRelations, setLoadingRelations] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [companyDialogOpen, setCompanyDialogOpen] = useState(false);
  // Estado del campo employeeCode (solo aplica en mode='create'):
  //  - autoGenerated: código sugerido por backend al abrir
  //  - codeError: mensaje si el código manual colisiona
  //  - checkingCode: spinner mientras consultamos disponibilidad
  const [autoGenerated, setAutoGenerated] = useState<string>('');
  const [codeError, setCodeError] = useState<string | null>(null);
  const [checkingCode, setCheckingCode] = useState(false);

  // Carga supervisores y empresas al abrir el diálogo. Se usan para los
  // dropdowns de "Supervisor primario", "Supervisor de respaldo" y "Empresa".
  useEffect(() => {
    if (!open) return;
    setLoadingRelations(true);
    Promise.all([
      supervisorService.list(false),
      companyService.list(true),
    ])
      .then(([sups, comps]) => {
        setSupervisors(sups);
        setCompanies(comps);
      })
      .catch(() => {
        setSupervisors([]);
        setCompanies([]);
      })
      .finally(() => setLoadingRelations(false));
  }, [open]);

  useEffect(() => {
    if (!open) return;
    if (mode === 'edit' && initial) {
      setForm({
        employeeCode: initial.employeeCode,
        fullName: initial.fullName,
        phone: initial.phone ?? '',
        email: initial.email ?? '',
        companyName: initial.companyName,
        companyType: initial.companyType,
        roleInPlant: initial.roleInPlant ?? '',
        hireDate: initial.hireDate ?? '',
        notes: initial.notes ?? '',
        isActive: initial.isActive,
        isWorkerInPlant: initial.isWorkerInPlant ?? true,
        isSupervisor: initial.isSupervisor ?? false,
        isCompanyManager: initial.isCompanyManager ?? false,
        supervisorId: initial.supervisorId ?? '',
        backupSupervisorId: initial.backupSupervisorId ?? '',
        companyId: initial.companyId ?? '',
        lastPrlTrainingDate: initial.lastPrlTrainingDate ?? '',
        prlValidMonths: initial.prlValidMonths ?? 12,
        supervisorNotes: initial.supervisorNotes ?? '',
      });
      setAutoGenerated('');
    } else {
      setForm(EMPTY);
      // En modo crear: pedimos al backend el próximo código libre y lo
      // pre-rellenamos. Si el admin lo edita y deja un código ocupado,
      // al perder el foco mostraremos un error.
      setAutoGenerated('');
      workerService.getNextCode()
        .then((code) => {
          setAutoGenerated(code);
          setForm((prev) => (prev.employeeCode === '' ? { ...prev, employeeCode: code } : prev));
        })
        .catch(() => { /* el admin podrá teclearlo a mano */ });
    }
    setError(null);
    setCodeError(null);
  }, [open, mode, initial]);

  const update = <K extends keyof FormState>(key: K, value: FormState[K]) => {
    setForm((prev) => ({ ...prev, [key]: value }));
  };

  // Comprueba la disponibilidad del código en backend cuando el admin cambia
  // el sugerido. Se llama desde onBlur para no spamear con cada tecla.
  const checkEmployeeCodeAvailability = async () => {
    if (mode !== 'create') return;
    const code = form.employeeCode.trim();
    setCodeError(null);
    if (code === '') {
      // Si vacía, restauramos el auto-sugerido para evitar dejar el formulario inválido.
      if (autoGenerated) update('employeeCode', autoGenerated);
      return;
    }
    // Si el código coincide con el auto-generado, lo damos por bueno sin
    // pedir al backend (acabamos de pedírselo al abrir).
    if (code === autoGenerated) return;
    try {
      setCheckingCode(true);
      const available = await workerService.checkCode(code);
      if (!available) {
        setCodeError(`El código "${code}" ya está en uso. Cámbialo por uno único.`);
      }
    } catch {
      // Falló la verificación — no bloqueamos al usuario; la unicidad final
      // la garantiza el constraint UNIQUE de la base.
    } finally {
      setCheckingCode(false);
    }
  };

  const handleSubmit = async () => {
    setSubmitting(true);
    setError(null);
    try {
      const payload = {
        fullName: form.fullName.trim(),
        phone: form.phone.trim() || null,
        email: form.email.trim() || null,
        companyName: form.companyName.trim(),
        companyType: form.companyType,
        roleInPlant: form.roleInPlant.trim() || null,
        hireDate: form.hireDate || null,
        notes: form.notes.trim() || null,
        // V13 fields
        isWorkerInPlant: form.isWorkerInPlant,
        isSupervisor: form.isSupervisor,
        isCompanyManager: form.isCompanyManager,
        supervisorId: form.supervisorId === '' ? null : Number(form.supervisorId),
        backupSupervisorId: form.backupSupervisorId === '' ? null : Number(form.backupSupervisorId),
        companyId: form.companyId === '' ? null : Number(form.companyId),
        lastPrlTrainingDate: form.lastPrlTrainingDate || null,
        prlValidMonths: form.prlValidMonths,
        supervisorNotes: form.supervisorNotes.trim() || null,
      };
      if (mode === 'create') {
        await workerService.create({
          ...payload,
          employeeCode: form.employeeCode.trim(),
        });
      } else if (initial) {
        await workerService.update(initial.id, {
          ...payload,
          isActive: form.isActive,
        });
      }
      onSaved();
      onClose();
    } catch (err: unknown) {
      const e = err as { response?: { data?: { message?: string }; status?: number } };
      const msg = e.response?.data?.message
        ?? (e.response?.status === 403 ? t('auth.noPermission') : t('common.error'));
      setError(msg);
    } finally {
      setSubmitting(false);
    }
  };

  // Para crear hace falta employeeCode + fullName. companyName es legacy pero
  // se mantiene como requerido para retro-compatibilidad con la tabla. Si el
  // code que el admin escribió manualmente colisiona, codeError bloquea el save.
  const isFormValid = !!(form.employeeCode.trim() && form.fullName.trim() && form.companyName.trim())
    && !codeError && !checkingCode;

  return (
    <>
    <Dialog open={open} onClose={submitting ? undefined : onClose} maxWidth="md" fullWidth>
      <DialogTitle>
        {mode === 'create' ? t('workers.dialog.createTitle') : t('workers.dialog.editTitle')}
      </DialogTitle>
      <DialogContent>
        <Stack spacing={2} sx={{ mt: 1 }}>
          {error && <Alert severity="error">{error}</Alert>}

          {/* ===== Identidad ===== */}
          <Typography variant="overline" color="text.secondary">Identidad</Typography>
          <TextField
            label={t('workers.dialog.fields.employeeCode')}
            value={form.employeeCode}
            onChange={(e) => {
              update('employeeCode', e.target.value);
              if (codeError) setCodeError(null);
            }}
            onBlur={checkEmployeeCodeAvailability}
            disabled={mode === 'edit' || submitting}
            required
            fullWidth
            error={!!codeError}
            helperText={
              codeError
                ?? (mode === 'create'
                  ? (checkingCode
                    ? 'Comprobando disponibilidad...'
                    : 'Se sugiere automáticamente. Puedes editarlo; se valida al perder el foco.')
                  : undefined)
            }
          />
          <TextField
            label={t('workers.dialog.fields.fullName')}
            value={form.fullName}
            onChange={(e) => update('fullName', e.target.value)}
            disabled={submitting}
            required
            fullWidth
          />
          <Stack direction="row" spacing={2}>
            <TextField
              label={t('workers.dialog.fields.email')}
              type="email"
              value={form.email}
              onChange={(e) => update('email', e.target.value)}
              disabled={submitting}
              fullWidth
            />
            <TextField
              label={t('workers.dialog.fields.phone')}
              value={form.phone}
              onChange={(e) => update('phone', e.target.value)}
              disabled={submitting}
              fullWidth
            />
          </Stack>

          {/* ===== Empresa y rol ===== */}
          <Divider sx={{ mt: 1 }} />
          <Typography variant="overline" color="text.secondary">Empresa y rol</Typography>
          <Stack direction="row" spacing={2}>
            <TextField
              label={t('workers.dialog.fields.companyName')}
              value={form.companyName}
              onChange={(e) => update('companyName', e.target.value)}
              disabled={submitting}
              required
              fullWidth
              helperText="Nombre legacy. Si la empresa existe en el catálogo, usar el selector de abajo."
            />
            <TextField
              select
              label={t('workers.dialog.fields.companyType')}
              value={form.companyType}
              onChange={(e) => update('companyType', e.target.value as CompanyType)}
              disabled={submitting}
              sx={{ minWidth: 180 }}
            >
              <MenuItem value="INTERNAL">{t('workers.companyType.INTERNAL')}</MenuItem>
              <MenuItem value="CONTRACTOR">{t('workers.companyType.CONTRACTOR')}</MenuItem>
              <MenuItem value="VISITOR">{t('workers.companyType.VISITOR')}</MenuItem>
            </TextField>
          </Stack>
          <Stack direction="row" spacing={1} alignItems="flex-start">
            <TextField
              select
              label="Empresa (catálogo)"
              value={form.companyId}
              onChange={(e) => update('companyId', e.target.value === '' ? '' : Number(e.target.value))}
              disabled={submitting || loadingRelations}
              fullWidth
              helperText={
                companies.length === 0
                  ? 'No hay empresas en el catálogo. Usa "+ Nueva empresa" o créala desde Empresas.'
                  : 'Permite escalar incidentes al manager de la empresa.'
              }
            >
              <MenuItem value="">(Sin empresa asignada del catálogo)</MenuItem>
              {companies.map((c) => (
                <MenuItem key={c.id} value={c.id}>
                  {c.name} — {c.managerName ?? 'sin manager'}
                </MenuItem>
              ))}
            </TextField>
            <Link
              component="button"
              type="button"
              underline="hover"
              onClick={() => setCompanyDialogOpen(true)}
              disabled={submitting}
              sx={{
                display: 'inline-flex',
                alignItems: 'center',
                gap: 0.5,
                mt: 1.5,
                whiteSpace: 'nowrap',
                fontSize: '0.875rem',
              }}
            >
              <AddCircleOutlineIcon fontSize="small" />
              Nueva empresa
            </Link>
          </Stack>
          <Stack direction="row" spacing={2}>
            <TextField
              label={t('workers.dialog.fields.roleInPlant')}
              value={form.roleInPlant}
              onChange={(e) => update('roleInPlant', e.target.value)}
              disabled={submitting}
              fullWidth
            />
            <TextField
              label={t('workers.dialog.fields.hireDate')}
              type="date"
              value={form.hireDate}
              onChange={(e) => update('hireDate', e.target.value)}
              disabled={submitting}
              InputLabelProps={{ shrink: true }}
              fullWidth
            />
          </Stack>

          {/* ===== Roles (V13) ===== */}
          <Divider sx={{ mt: 1 }} />
          <Typography variant="overline" color="text.secondary">Roles</Typography>
          <Typography variant="caption" color="text.secondary">
            Una persona puede tener varios roles. Marca los que correspondan.
          </Typography>
          <Stack direction="row" spacing={3} sx={{ flexWrap: 'wrap' }}>
            <FormControlLabel
              control={
                <Checkbox
                  checked={form.isWorkerInPlant}
                  onChange={(e) => update('isWorkerInPlant', e.target.checked)}
                  disabled={submitting}
                />
              }
              label="Trabajador en planta"
            />
            <FormControlLabel
              control={
                <Checkbox
                  checked={form.isSupervisor}
                  onChange={(e) => update('isSupervisor', e.target.checked)}
                  disabled={submitting}
                />
              }
              label="Es supervisor"
            />
            <FormControlLabel
              control={
                <Checkbox
                  checked={form.isCompanyManager}
                  onChange={(e) => update('isCompanyManager', e.target.checked)}
                  disabled={submitting}
                />
              }
              label="Es manager de empresa"
            />
          </Stack>

          {/* ===== Supervisión ===== */}
          {form.isWorkerInPlant && (
            <>
              <Divider sx={{ mt: 1 }} />
              <Typography variant="overline" color="text.secondary">Supervisión</Typography>
              <Stack direction="row" spacing={2}>
                <TextField
                  select
                  label="Supervisor primario"
                  value={form.supervisorId}
                  onChange={(e) => update('supervisorId', e.target.value === '' ? '' : Number(e.target.value))}
                  disabled={submitting || loadingRelations}
                  fullWidth
                  helperText={
                    supervisors.length === 0
                      ? 'No hay supervisores. Marca el flag "Es supervisor" en alguna persona.'
                      : 'Recibe escalado de las alertas del trabajador.'
                  }
                >
                  <MenuItem value="">(Sin supervisor)</MenuItem>
                  {supervisors.map((s) => (
                    <MenuItem key={s.id} value={s.id}>
                      {s.fullName}
                      {s.phone ? ` · ${s.phone}` : ''}
                    </MenuItem>
                  ))}
                </TextField>
                <TextField
                  select
                  label="Supervisor de respaldo"
                  value={form.backupSupervisorId}
                  onChange={(e) => update('backupSupervisorId', e.target.value === '' ? '' : Number(e.target.value))}
                  disabled={submitting || loadingRelations}
                  fullWidth
                  helperText="Escalado si el primario no contesta."
                >
                  <MenuItem value="">(Sin backup)</MenuItem>
                  {supervisors.map((s) => (
                    <MenuItem key={s.id} value={s.id}>
                      {s.fullName}
                    </MenuItem>
                  ))}
                </TextField>
              </Stack>
              <TextField
                label="Notas del supervisor (privadas)"
                value={form.supervisorNotes}
                onChange={(e) => update('supervisorNotes', e.target.value)}
                disabled={submitting}
                multiline
                rows={2}
                fullWidth
                helperText="Notas que solo ven supervisor / admin / seguridad."
              />
            </>
          )}

          {/* ===== PRL ===== */}
          {form.isWorkerInPlant && (
            <>
              <Divider sx={{ mt: 1 }} />
              <Typography variant="overline" color="text.secondary">Formación PRL</Typography>
              <Stack direction="row" spacing={2}>
                <TextField
                  label="Fecha último curso PRL"
                  type="date"
                  value={form.lastPrlTrainingDate}
                  onChange={(e) => update('lastPrlTrainingDate', e.target.value)}
                  disabled={submitting}
                  InputLabelProps={{ shrink: true }}
                  fullWidth
                  helperText="Vacío = sin registro / pendiente."
                />
                <TextField
                  label="Meses de validez"
                  type="number"
                  value={form.prlValidMonths}
                  onChange={(e) => update('prlValidMonths', Number(e.target.value) || 12)}
                  disabled={submitting}
                  inputProps={{ min: 1, max: 60 }}
                  sx={{ width: 200 }}
                />
              </Stack>
            </>
          )}

          {/* ===== Notas generales ===== */}
          <Divider sx={{ mt: 1 }} />
          <TextField
            label={t('workers.dialog.fields.notes')}
            value={form.notes}
            onChange={(e) => update('notes', e.target.value)}
            disabled={submitting}
            multiline
            rows={2}
            fullWidth
          />

          {mode === 'edit' && (
            <FormControlLabel
              control={
                <Switch
                  checked={form.isActive}
                  onChange={(e) => update('isActive', e.target.checked)}
                  disabled={submitting}
                />
              }
              label={t('workers.dialog.fields.isActive')}
            />
          )}
        </Stack>
      </DialogContent>
      <DialogActions>
        <Button onClick={onClose} disabled={submitting}>
          {t('common.cancel')}
        </Button>
        <Button
          onClick={handleSubmit}
          variant="contained"
          disabled={!isFormValid || submitting}
        >
          {t('common.save')}
        </Button>
      </DialogActions>
    </Dialog>

    <CompanyDialog
      open={companyDialogOpen}
      mode="create"
      onClose={() => setCompanyDialogOpen(false)}
      onSaved={(created) => {
        // Añade al dropdown sin recargar; auto-selecciona la empresa.
        setCompanies((prev) => [...prev.filter((c) => c.id !== created.id), created]);
        setForm((prev) => ({
          ...prev,
          companyId: created.id,
          // Rellena los campos legacy si estaban vacíos — no pisa lo que el
          // usuario ya hubiera escrito.
          companyName: prev.companyName.trim() === '' ? created.name : prev.companyName,
          companyType: prev.companyType === 'INTERNAL' && prev.companyName.trim() === ''
            ? created.type
            : prev.companyType,
        }));
      }}
    />
    </>
  );
}

export default WorkerDialog;
